[package]
name = "resources"
version = "0.1.0"
authors = ["ManicRobot <manicrobot@protonmail.com>"]
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
pci-ids = "0.2.4"
glob = "0.3.0"
lazy_static = "1.4.0"
anyhow = "1.0.62"
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.9"
gtk = { version = "0.4", package = "gtk4" }
adw = { version = "0.1.1", package = "libadwaita" }
nparse = "0.0.4"
regex = "1.6.0"
serde_json = "1.0"
sysconf = "0.3.4"
zbus = "3.0.0"
nvml-wrapper = "0.8.0"