[package]
name = "resources"
version = "0.1.0"
authors = ["nokyan <nokyan@tuta.io>"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
pci-ids = "0.2.5"
glob = "0.3.1"
anyhow = "1.0.71"
log = "0.4.19"
pretty_env_logger = "0.5"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.18"
gtk = { version = "0.7.1", features = ["v4_8"], package = "gtk4" }
adw = { version = "0.5.2", features = ["v1_3"], package = "libadwaita" }
nparse = "0.0.4"
regex = "1.8.4"
serde_json = "1.0"
sysconf = "0.3.4"
nvml-wrapper = "0.9.0"
futures-util = "0.3.28"
unescape = "0.1.0"
nix = { version = "0.26.2", features = ["signal"] }
users = "0.11.0"
plotters = { version = "0.3.4", default_features = false, features = [
    "area_series",
] }
plotters-cairo = { git = "https://github.com/nokyan/plotters-cairo", branch = "cairo-rs-0.18" }
serde = { version = "1.0.180", features = ["serde_derive"] }
rmp-serde = "1.1.2"
async-process = "1.7.0"
rust-ini = "0.19.0"
gtk-macros = "0.3.0"
