[package]
name = "resources"
version = "1.4.0"
authors = ["nokyan <nokyan@tuta.io>"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
process-data = { path = "lib/process_data" }
glob = "0.3.1"
anyhow = "1.0.86"
log = "0.4.21"
pretty_env_logger = "0.5"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.8.2", features = ["v4_10"], package = "gtk4" }
adw = { version = "0.6.0", features = ["v1_5"], package = "libadwaita" }
regex = "1.10.4"
sysconf = "0.3.4"
nvml-wrapper = "0.10.0"
nix = { version = "0.29.0", default_features = false, features = ["signal"] }
plotters = { version = "0.3.6", default_features = false, features = [
    "area_series",
] }
plotters-cairo = "0.6.0"
serde = { version = "1.0.203", features = ["serde_derive"] }
rmp-serde = "1.3.0"
rust-ini = "0.21.0"
gtk-macros = "0.3.0"
strum = "0.26.2"
strum_macros = "0.26.3"
once_cell = "1.19.0"
hashbrown = "0.14.5"
paste = "1.0.15"
num_cpus = "1.16.0"
async-channel = "2.3.1"
