name: "\U0001F41E Bug Report"
description: Create a bug report to help us fix it
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I searched the existing issues and did not find anything similar.
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide information about your environment.
    placeholder: |
      Program Version 3.3.2 (You can find this in the About dialog)
      Package type: Flatpak
      System: Ubuntu 22.04
      Hardware info(if applicable): Intel i7-7700k, 32GB RAM, Nvidia GTX 1080
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false